# Generated by Django 3.2.5 on 2022-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
