# Generated by Django 3.2.5 on 2022-12-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('log_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st.teacherslog')),
            ],
        ),
    ]
