# Generated by Django 3.2.5 on 2023-01-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_teachers_teacherslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='Teacherslog',
        ),
    ]
