# Generated by Django 3.2.5 on 2023-01-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('st', '0004_auto_20230106_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='auth.user')),
                ('emprole', models.CharField(choices=[('AD', 'Admin'), ('USR', 'User')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='log_id',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
