# Generated by Django 3.2.5 on 2023-01-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20230117_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
