# Generated by Django 3.2.5 on 2023-01-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_auto_20230117_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='Question',
            new_name='question',
        ),
    ]
