# Generated by Django 3.2.5 on 2023-01-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0006_rename_question_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='st.topic'),
            preserve_default=False,
        ),
    ]
