# Generated by Django 3.2.5 on 2023-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0007_answers_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=600),
        ),
    ]
